replicaCount: 4

image:
  tag: "2.0.0"

environment:
  SPRING_PROFILES_ACTIVE: prod

features:
  notification: true
  audit: true
  databaseChange: true

autoscaling:
  enabled: true
  minReplicas: 4
  maxReplicas: 10
  targetCPUUtilizationPercentage: 65
